name: expense_tracker
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.260
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  firebase_core: ^3.6.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  uuid: ^4.5.1
  expense_repository:
    path: packages/expense_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
