name: expense_repo
description: "The repository for the expense tracker app"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


