// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0m7LuN41f68DVPdmm0iYNQq84rqwo6cw',
    appId: '1:156725179360:web:e300a119ab424fa30ab185',
    messagingSenderId: '156725179360',
    projectId: 'expense-tracker-276d4',
    authDomain: 'expense-tracker-276d4.firebaseapp.com',
    storageBucket: 'expense-tracker-276d4.appspot.com',
    measurementId: 'G-W8PCM45H7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDApp0dK63MzLLGhmz_pFkb6ovQvMvyPQ',
    appId: '1:156725179360:android:e32b20dfee301b9f0ab185',
    messagingSenderId: '156725179360',
    projectId: 'expense-tracker-276d4',
    storageBucket: 'expense-tracker-276d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNKbm6Wjr0rTCU1HiqBcK-WZ_T5rAHjig',
    appId: '1:156725179360:ios:43ecaf2c39729f060ab185',
    messagingSenderId: '156725179360',
    projectId: 'expense-tracker-276d4',
    storageBucket: 'expense-tracker-276d4.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNKbm6Wjr0rTCU1HiqBcK-WZ_T5rAHjig',
    appId: '1:156725179360:ios:43ecaf2c39729f060ab185',
    messagingSenderId: '156725179360',
    projectId: 'expense-tracker-276d4',
    storageBucket: 'expense-tracker-276d4.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0m7LuN41f68DVPdmm0iYNQq84rqwo6cw',
    appId: '1:156725179360:web:5099f1cd646f46380ab185',
    messagingSenderId: '156725179360',
    projectId: 'expense-tracker-276d4',
    authDomain: 'expense-tracker-276d4.firebaseapp.com',
    storageBucket: 'expense-tracker-276d4.appspot.com',
    measurementId: 'G-6518XCEDMR',
  );
}
